package xyz.jangle.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BsRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public BsRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRolIdIsNull() {
            addCriterion("rol_id is null");
            return (Criteria) this;
        }

        public Criteria andRolIdIsNotNull() {
            addCriterion("rol_id is not null");
            return (Criteria) this;
        }

        public Criteria andRolIdEqualTo(Integer value) {
            addCriterion("rol_id =", value, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdNotEqualTo(Integer value) {
            addCriterion("rol_id <>", value, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdGreaterThan(Integer value) {
            addCriterion("rol_id >", value, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rol_id >=", value, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdLessThan(Integer value) {
            addCriterion("rol_id <", value, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdLessThanOrEqualTo(Integer value) {
            addCriterion("rol_id <=", value, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdIn(List<Integer> values) {
            addCriterion("rol_id in", values, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdNotIn(List<Integer> values) {
            addCriterion("rol_id not in", values, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdBetween(Integer value1, Integer value2) {
            addCriterion("rol_id between", value1, value2, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rol_id not between", value1, value2, "rolId");
            return (Criteria) this;
        }

        public Criteria andRolNameIsNull() {
            addCriterion("rol_name is null");
            return (Criteria) this;
        }

        public Criteria andRolNameIsNotNull() {
            addCriterion("rol_name is not null");
            return (Criteria) this;
        }

        public Criteria andRolNameEqualTo(String value) {
            addCriterion("rol_name =", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameNotEqualTo(String value) {
            addCriterion("rol_name <>", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameGreaterThan(String value) {
            addCriterion("rol_name >", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameGreaterThanOrEqualTo(String value) {
            addCriterion("rol_name >=", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameLessThan(String value) {
            addCriterion("rol_name <", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameLessThanOrEqualTo(String value) {
            addCriterion("rol_name <=", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameLike(String value) {
            addCriterion("rol_name like", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameNotLike(String value) {
            addCriterion("rol_name not like", value, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameIn(List<String> values) {
            addCriterion("rol_name in", values, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameNotIn(List<String> values) {
            addCriterion("rol_name not in", values, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameBetween(String value1, String value2) {
            addCriterion("rol_name between", value1, value2, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolNameNotBetween(String value1, String value2) {
            addCriterion("rol_name not between", value1, value2, "rolName");
            return (Criteria) this;
        }

        public Criteria andRolCodeIsNull() {
            addCriterion("rol_code is null");
            return (Criteria) this;
        }

        public Criteria andRolCodeIsNotNull() {
            addCriterion("rol_code is not null");
            return (Criteria) this;
        }

        public Criteria andRolCodeEqualTo(String value) {
            addCriterion("rol_code =", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeNotEqualTo(String value) {
            addCriterion("rol_code <>", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeGreaterThan(String value) {
            addCriterion("rol_code >", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeGreaterThanOrEqualTo(String value) {
            addCriterion("rol_code >=", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeLessThan(String value) {
            addCriterion("rol_code <", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeLessThanOrEqualTo(String value) {
            addCriterion("rol_code <=", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeLike(String value) {
            addCriterion("rol_code like", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeNotLike(String value) {
            addCriterion("rol_code not like", value, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeIn(List<String> values) {
            addCriterion("rol_code in", values, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeNotIn(List<String> values) {
            addCriterion("rol_code not in", values, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeBetween(String value1, String value2) {
            addCriterion("rol_code between", value1, value2, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolCodeNotBetween(String value1, String value2) {
            addCriterion("rol_code not between", value1, value2, "rolCode");
            return (Criteria) this;
        }

        public Criteria andRolStatusIsNull() {
            addCriterion("rol_status is null");
            return (Criteria) this;
        }

        public Criteria andRolStatusIsNotNull() {
            addCriterion("rol_status is not null");
            return (Criteria) this;
        }

        public Criteria andRolStatusEqualTo(Integer value) {
            addCriterion("rol_status =", value, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusNotEqualTo(Integer value) {
            addCriterion("rol_status <>", value, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusGreaterThan(Integer value) {
            addCriterion("rol_status >", value, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("rol_status >=", value, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusLessThan(Integer value) {
            addCriterion("rol_status <", value, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusLessThanOrEqualTo(Integer value) {
            addCriterion("rol_status <=", value, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusIn(List<Integer> values) {
            addCriterion("rol_status in", values, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusNotIn(List<Integer> values) {
            addCriterion("rol_status not in", values, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusBetween(Integer value1, Integer value2) {
            addCriterion("rol_status between", value1, value2, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andRolStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("rol_status not between", value1, value2, "rolStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRolExtends1IsNull() {
            addCriterion("rol_extends1 is null");
            return (Criteria) this;
        }

        public Criteria andRolExtends1IsNotNull() {
            addCriterion("rol_extends1 is not null");
            return (Criteria) this;
        }

        public Criteria andRolExtends1EqualTo(String value) {
            addCriterion("rol_extends1 =", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1NotEqualTo(String value) {
            addCriterion("rol_extends1 <>", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1GreaterThan(String value) {
            addCriterion("rol_extends1 >", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1GreaterThanOrEqualTo(String value) {
            addCriterion("rol_extends1 >=", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1LessThan(String value) {
            addCriterion("rol_extends1 <", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1LessThanOrEqualTo(String value) {
            addCriterion("rol_extends1 <=", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1Like(String value) {
            addCriterion("rol_extends1 like", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1NotLike(String value) {
            addCriterion("rol_extends1 not like", value, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1In(List<String> values) {
            addCriterion("rol_extends1 in", values, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1NotIn(List<String> values) {
            addCriterion("rol_extends1 not in", values, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1Between(String value1, String value2) {
            addCriterion("rol_extends1 between", value1, value2, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends1NotBetween(String value1, String value2) {
            addCriterion("rol_extends1 not between", value1, value2, "rolExtends1");
            return (Criteria) this;
        }

        public Criteria andRolExtends2IsNull() {
            addCriterion("rol_extends2 is null");
            return (Criteria) this;
        }

        public Criteria andRolExtends2IsNotNull() {
            addCriterion("rol_extends2 is not null");
            return (Criteria) this;
        }

        public Criteria andRolExtends2EqualTo(String value) {
            addCriterion("rol_extends2 =", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2NotEqualTo(String value) {
            addCriterion("rol_extends2 <>", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2GreaterThan(String value) {
            addCriterion("rol_extends2 >", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2GreaterThanOrEqualTo(String value) {
            addCriterion("rol_extends2 >=", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2LessThan(String value) {
            addCriterion("rol_extends2 <", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2LessThanOrEqualTo(String value) {
            addCriterion("rol_extends2 <=", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2Like(String value) {
            addCriterion("rol_extends2 like", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2NotLike(String value) {
            addCriterion("rol_extends2 not like", value, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2In(List<String> values) {
            addCriterion("rol_extends2 in", values, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2NotIn(List<String> values) {
            addCriterion("rol_extends2 not in", values, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2Between(String value1, String value2) {
            addCriterion("rol_extends2 between", value1, value2, "rolExtends2");
            return (Criteria) this;
        }

        public Criteria andRolExtends2NotBetween(String value1, String value2) {
            addCriterion("rol_extends2 not between", value1, value2, "rolExtends2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_role
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 18 10:45:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}