package xyz.jangle.demoname.model;

import java.util.Date;

public class BsRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.rol_id
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private Integer rolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.rol_name
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private String rolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.rol_code
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private String rolCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.rol_status
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private Integer rolStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.create_time
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.update_time
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.rol_extends1
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private String rolExtends1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_role.rol_extends2
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    private String rolExtends2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.rol_id
     *
     * @return the value of bs_role.rol_id
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public Integer getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.rol_id
     *
     * @param rolId the value for bs_role.rol_id
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.rol_name
     *
     * @return the value of bs_role.rol_name
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public String getRolName() {
        return rolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.rol_name
     *
     * @param rolName the value for bs_role.rol_name
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setRolName(String rolName) {
        this.rolName = rolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.rol_code
     *
     * @return the value of bs_role.rol_code
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public String getRolCode() {
        return rolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.rol_code
     *
     * @param rolCode the value for bs_role.rol_code
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setRolCode(String rolCode) {
        this.rolCode = rolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.rol_status
     *
     * @return the value of bs_role.rol_status
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public Integer getRolStatus() {
        return rolStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.rol_status
     *
     * @param rolStatus the value for bs_role.rol_status
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setRolStatus(Integer rolStatus) {
        this.rolStatus = rolStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.create_time
     *
     * @return the value of bs_role.create_time
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.create_time
     *
     * @param createTime the value for bs_role.create_time
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.update_time
     *
     * @return the value of bs_role.update_time
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.update_time
     *
     * @param updateTime the value for bs_role.update_time
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.rol_extends1
     *
     * @return the value of bs_role.rol_extends1
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public String getRolExtends1() {
        return rolExtends1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.rol_extends1
     *
     * @param rolExtends1 the value for bs_role.rol_extends1
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setRolExtends1(String rolExtends1) {
        this.rolExtends1 = rolExtends1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_role.rol_extends2
     *
     * @return the value of bs_role.rol_extends2
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public String getRolExtends2() {
        return rolExtends2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_role.rol_extends2
     *
     * @param rolExtends2 the value for bs_role.rol_extends2
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    public void setRolExtends2(String rolExtends2) {
        this.rolExtends2 = rolExtends2;
    }
}