package xyz.jangle.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyz.jangle.model.BsRole;
import xyz.jangle.model.BsRoleExample;

public interface BsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    long countByExample(BsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int deleteByExample(BsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int deleteByPrimaryKey(Integer rolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int insert(BsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int insertSelective(BsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    List<BsRole> selectByExample(BsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    BsRole selectByPrimaryKey(Integer rolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") BsRole record, @Param("example") BsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByExample(@Param("record") BsRole record, @Param("example") BsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByPrimaryKeySelective(BsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByPrimaryKey(BsRole record);
}