package xyz.jangle.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyz.jangle.model.DRole;
import xyz.jangle.model.DRoleExample;

public interface DRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    long countByExample(DRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int deleteByExample(DRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int deleteByPrimaryKey(Integer rolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int insert(DRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int insertSelective(DRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    List<DRole> selectByExample(DRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    DRole selectByPrimaryKey(Integer rolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") DRole record, @Param("example") DRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByExample(@Param("record") DRole record, @Param("example") DRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByPrimaryKeySelective(DRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_role
     *
     * @mbg.generated Tue Sep 18 10:45:18 CST 2018
     */
    int updateByPrimaryKey(DRole record);
}